### ISSUE TITLE
blank line in hypothesis

### ISSUE THREAD

**Issue by Gldkslfmsd** [rwth-i6/CharacTER#2]
Hello,

I have a hypothesis files where some lines were translated as blank lines. It causes following error:

```
Traceback (most recent call last):
  File "./CharacTER.py", line 339, in <module>
    main()
  File "./CharacTER.py", line 325, in main
    score = cer(hyp, ref)
  File "./CharacTER.py", line 48, in cer
    return edit_cost / len(shifted_chars)
ZeroDivisionError: division by zero
```

**Comment by Nintendo-Wei** [comment]
Hi Gldkslfmsd,

Sorry for the late reply. Now this issue should be fixed.
Many thanks for reporting the error!

Cheers
Wei
